# Generated by Django 2.2.12 on 2020-09-28 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('gallery', models.ImageField(upload_to='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='apps.Image'),
        ),
    ]
