# Generated by Django 2.2.12 on 2020-10-01 18:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200928_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('duration', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('unit_name', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('image', models.ManyToManyField(blank=True, default=None, null=True, to='apps.Image')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_suplier_user', to='apps.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('duration', models.CharField(blank=True, max_length=128)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('unit_name', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('image', models.ManyToManyField(blank=True, default=None, null=True, to='apps.Image')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_suplier_user', to='apps.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ts_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('review', models.CharField(blank=True, max_length=256)),
                ('rate', models.FloatField(default=0)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_rate_user', to='apps.Activity')),
                ('stay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay_rate_user', to='apps.Stay')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_rate_user', to='apps.Tour')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_user', to='apps.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
