# Generated by Django 2.2.12 on 2020-10-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20201003_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cover_image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='place',
            name='square_image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
