# Generated by Django 2.2.12 on 2020-10-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20201003_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cover_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='place',
            name='square_image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
